- WIP, not working, getting: ``` Step 12/17 : RUN cargo install --path .  ---> Running in cca6d4e888c0   Installing graphql_minizinc_server v0.1.0 (/usr/src/app)     Updating crates.io index    Compiling graphql_minizinc_server v0.1.0 (/usr/src/app) error[E0432]: unresolved import `graphql_minizinc_server::graphql`  --> src/bin/server.rs:3:30   | 3 | use graphql_minizinc_server::graphql::graphql_server;   |                              ^^^^^^^ could not find `graphql` in `graphql_minizinc_server`
error[E0432]: unresolved import `graphql_minizinc_server::parameters_from_model`
 --> src/bin/server.rs:4:5
  |
4 | use graphql_minizinc_server::parameters_from_model;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `parameters_from_model` in the root

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: failed to compile `graphql_minizinc_server v0.1.0 (/usr/src/app)`, intermediate artifacts can be found at `/usr/src/app/target`

Caused by:
  could not compile `graphql_minizinc_server`

To learn more, run the command again with --verbose.
```